### ISSUE TITLE
[3pts] Create users controller

### ISSUE THREAD

**Issue by DarioAlessioR** [Home-Sharing-Team/final-capstone-Project-Back-End#6]
Create controller
Create methods
Create allowed params

**Comment by David-Verde** [comment]
Created API users Controller
Created API Users Model
The Users can be generated in JSON format and can be called from the Thunder Client
The user can be delete and update from the Thunder Client
![Image](https://user-images.githubusercontent.com/99683363/200855468-84e56981-708d-435d-8a0d-9b117ab48a24.png)
